version: '3.6'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  